### ISSUE TITLE
Bread razzia page for TREO

### ISSUE THREAD

**Issue by Rene4100** [f-klubben/stregsystem#25]
Currently, when TREO are doing bread razzia we have to go into the stregsystem admin page, to validate a fember. This is not suitable since normal fembers can, "slight of hand" change information about themselves or other fembers, while the TREO menber i busy checking the other people passing by.
Therefore it could be good to have a simple page where we can do the validation of fembers. 
It needs a text input field - and a validate button
When a user presses the button then, a big green checkmark together with info about the fember, Firstname, Lastname, and balance, has to be shown.
If the user does not exist in the stregsystem, then a big red X is shown together with a text indicating that the user is not a member or found in the stregsystem

**Comment by VirtualSatai** [comment]
https://github.com/f-klubben/stregsystemet/

**Comment by HenrikOssipoff** [comment]
@Rene4100 there actually exists a Razzia tool, or rather, there used to exist one. I know Dion Christensen made one, because we were tired of the manual work in validating people.

Not sure if he still has it, but he might. He's on the FIT mailing list as far as I'm aware.
