### ISSUE TITLE
License

### ISSUE THREAD

**Issue by HenrikOssipoff** [f-klubben/stregsystem#3]
We should add a license.

I'm a fan if WTFPL (http://www.wtfpl.net). Any objections?

**Comment by fishbacon** [comment]
Personally I like one which is actually legally binding but still permissive:
[Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29)

**Comment by HenrikOssipoff** [comment]
So we settled on "THE LIMFJORDS-PORTER-WARE LICENSE".

It is as follows (I've updated the e-mail and bumped the revision accordingly):

```
"THE LIMFJORDS-PORTER-WARE LICENSE" (Revision 43):
<fit@fklub.dk> wrote this file. As long as you retain this
notice you can do whatever you want with this stuff. If we meet some
day, and you think this stuff is worth it, you can buy us a
Limfjords-porter in return.
```

If this sounds good to everyone, I'll drop a PR.

Tagging @mchro and @jones-g for visibility.

EDIT: changed a "me" to "us".
